default: &default
  adapter: postgresql
  encoding: utf-8
  reconnect: false
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: stuylaunch_development

test:
  <<: *default
  database: stuylaunch_development
